# Site settings
title: Qiongyu Huang
email: qhuang@umg.edu
description: "Ph.D candidate in Geography at the University of Maryland, College Park"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qiongyuhuang.github.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  qiongyuhuang

# Build settings
markdown: kramdown
